### ISSUE TITLE
What about API keys?

### ISSUE THREAD

**Issue by shanow7** [1a11/o8#1]
where I have to insert the api keys?

**Comment by 1a11** [comment]
Hey. You don't have to. O8 is a completely standalone tool. In other words, fuck paid APIs

**Comment by shanow7** [comment]
something it's wrong

![image](https://user-images.githubusercontent.com/37192410/83946794-43967400-a813-11ea-8a10-bbc6a8edc91a.png)

**Comment by 1a11** [comment]
First of all, name-things doesn't work for now, till I finish working on that. 
Second, Gravatar lookup uses an e-mail address to find any record with it into its database.

**Comment by shanow7** [comment]
Which of the modules 0-7 works?

**Comment by 1a11** [comment]
Every module

**Comment by shanow7** [comment]
![image](https://user-images.githubusercontent.com/37192410/83955306-c9d1ab00-a851-11ea-8d8e-dc963d28901c.png)

why doesn't work?

**Comment by 1a11** [comment]
First of all, don't flash your info over the Internet. Second, would you mind telling me what kinds of data you entered?

**Comment by 1a11** [comment]
Also, your command line output doesn't seem right. Can you please ensure, everything is installed, including sherlock and phoneinfoga modules

**Comment by shanow7** [comment]
I flash my information because you can see what data is being input, except that there is nothing in the installation description about installing sherlock

**Comment by 1a11** [comment]
That's what we are going to do. Go through that checklist and verify, everything is working correctly:

- You are using python > 3.6.0
- You are operating one of supported OSs
- You installed everything from requirements.txt
- H8mail is up and running

For now, I can see, your checks list is empty. It prints 

`[]`

but it actually needs to be something like that:

`{'0': {'url': 'http://ip-api.com/json/{}+ip', 'type': 'external'}, '1': {'url': 'https://gravatar.com/{}+ehash', 'type': 'external'}, '2': {'url': 'https://intelx.io/?s={}+email', 'type': 'external'}, '3': {'url': 'https://haveibeenpwned.com/unifiedsearch/{}+email', 'type': 'external'}, '4': {'url': 'local://okcheck/', 'type': 'local'}, '5': {'url': 'local://h8mail/', 'type': 'local'}, '6': {'url': 'local://sherlock/', 'type': 'local'}, '7': {'url': 'local://phoneinfoga/', 'type': 'local'}}`

My Telegram is @nolewit if it would be more comfortable to talk that way

**Comment by 1a11** [comment]
The error got fixed with last commit  #61daec5. It should work now. My fault
